### ISSUE TITLE
 training environment

### ISSUE THREAD

**Issue by zhoujh2020** [djiajunustc/Voxel-R-CNN#1]
What is the minimum training environment requirement( the required gpus)?

**Comment by djiajunustc** [comment]
You can use 1 GPU with batch size set as 4, or 2 GPUs with batch size set as 8.

**Comment by gy-zkj** [comment]
> You can use 1 GPU with batch size set as 4, or 2 GPUs with batch size set as 8.

When I use RTX2060， I always report that the memory is not enough, batch size=2 still doesn’t work
