### ISSUE TITLE
code of voxel roi pooling

### ISSUE THREAD

**Issue by mc171819** [djiajunustc/Voxel-R-CNN#14]
hi, i can't find your code about voxel roi pooling, can you tell me where is it?

**Comment by djiajunustc** [comment]
Hi, 
Please refer to Voxel-R-CNN/pcdet/ops/pointnet2/pointnet2_stack/voxel_pool_modules.p

**Comment by djiajunustc** [comment]
Hi,
Please refer to Voxel-R-CNN/pcdet/ops/pointnet2/pointnet2_stack/voxel_pool_modules.py
