### ISSUE TITLE
How to evaluate my own point cloud

### ISSUE THREAD

**Issue by Wes-Wang** [djiajunustc/Voxel-R-CNN#2]
Hello, I was hoping you could give me some guidance on the syntax for evaluating my own set of point clouds. I was not able to figure out how to do this through the files. Thank you!

**Comment by djiajunustc** [comment]
Hi，

You can convert your data format to the similar format of KITTI.
And use the kitii_dataset.py to load your own dataset.

Remember to convert the GT boxes from the coordinates of annotation to that of the LiDAR.
Please refer to https://github.com/djiajunustc/Voxel-R-CNN/blob/main/pcdet/datasets/kitti/kitti_dataset.py#L370

And if you only annotate the objects in the FOV, please refer to https://github.com/djiajunustc/Voxel-R-CNN/blob/main/pcdet/datasets/kitti/kitti_dataset.py#L354 to remove the points out of range.

**Comment by djiajunustc** [comment]
No extra questions for the past 50 days
