### ISSUE TITLE
Config on waymo dataset

### ISSUE THREAD

**Issue by Eaphan** [djiajunustc/Voxel-R-CNN#21]
Thanks for your sharing. Can you supply the config of voxel r-cnn on waymo dataset?

**Comment by djiajunustc** [comment]
Hi @Viczyf ,
I have added the config of Voxel R-CNN on Waymo Open Dataset in OpenPCDet (https://github.com/open-mmlab/OpenPCDet). Please refer to it.

**Comment by Eaphan** [comment]
Thanks
