### ISSUE TITLE
eval result of models trained with voxel_rcnn_3classes.yaml

### ISSUE THREAD

**Issue by code-roamer** [djiajunustc/Voxel-R-CNN#22]
Hello, thanks for your great work. I have trained voxel-rcnn with voxel_rcnn_3class.yaml, but the result is worse than voxel_rcnn_car.yaml. Is that right? How can I get the result of pedestrain and cyclist in KITTI dataset? thanks!

results are as follows:
2022-03-07 20:27:15,298   INFO  Car AP@0.70, 0.70, 0.70:
bbox AP:95.3898, 83.2715, 77.2035
bev  AP:89.3690, 76.6368, 75.2530
3d   AP:87.9943, 72.9119, 67.3161
aos  AP:95.29, 82.68, 76.53
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:97.2515, 83.4524, 81.0170
bev  AP:94.2792, 79.8192, 75.6973
3d   AP:90.7316, 72.6871, 69.4763
aos  AP:97.16, 82.88, 80.15
Car AP@0.70, 0.50, 0.50:
bbox AP:95.3898, 83.2715, 77.2035
bev  AP:95.3354, 83.3392, 82.9096
3d   AP:95.2646, 83.1027, 77.0240
aos  AP:95.29, 82.68, 76.53
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:97.2515, 83.4524, 81.0170
bev  AP:97.1493, 84.8501, 82.5885
3d   AP:97.1129, 84.7085, 80.8528
aos  AP:97.16, 82.88, 80.15
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:48.4417, 43.1507, 42.1027
bev  AP:48.4228, 41.3880, 40.1097
3d   AP:46.5401, 39.7380, 38.7178
aos  AP:44.54, 39.19, 37.68
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:46.3712, 41.4821, 39.3516
bev  AP:46.6629, 39.1686, 37.5176
3d   AP:44.6500, 37.2929, 35.4425
aos  AP:41.86, 36.81, 34.38
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:48.4417, 43.1507, 42.1027
bev  AP:53.0485, 47.6899, 47.0767
3d   AP:52.9010, 47.4667, 46.8729
aos  AP:44.54, 39.19, 37.68
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:46.3712, 41.4821, 39.3516
bev  AP:52.9300, 45.9471, 44.6889
3d   AP:52.6937, 45.7476, 44.4331
aos  AP:41.86, 36.81, 34.38
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:86.7945, 74.1553, 72.5625
bev  AP:85.1334, 70.5727, 66.6534
3d   AP:85.0664, 67.6590, 65.3969
aos  AP:85.57, 72.61, 70.92
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:89.4240, 74.4265, 72.4647
bev  AP:87.7896, 70.5118, 67.8602
3d   AP:87.0270, 68.8757, 65.8546
aos  AP:88.12, 72.82, 70.74
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:86.7945, 74.1553, 72.5625
bev  AP:85.1736, 70.7908, 68.8701
3d   AP:85.1736, 70.7908, 68.8701
aos  AP:85.57, 72.61, 70.92
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:89.4240, 74.4265, 72.4647
bev  AP:87.8156, 71.3646, 68.7342
3d   AP:87.8156, 71.3646, 68.7342
aos  AP:88.12, 72.82, 70.74

**Comment by hahhahahhaha** [comment]
Hello, a question has been bothering me for a long time. Could you please help me answer it? In training, voxel_ rcnn_ Error reported by torch. cat() when car. yaml RuntimeError: Sizes of Tensors must match exception in Dimension 2. Got 226 and 225 (The offering index is 0)
